### ISSUE TITLE
[bug] TemplateNotFound in case of imported config

### ISSUE THREAD

**Issue by katoquro** [deadc0de6/dotdrop#226]
Dotdrop version (and git commit if run from source): v1.0.0
Using dotdrop: as a submodule

**Describe the bug**

I'm trying to split my configs logically depending on machine type (like servers and machines with Desktop environment). So I have main config file `config.yaml` with `dotpath: dotfiles-common` 
and `config-de.yaml` in the same folder with `dotpath: dotfiles-de` 
When I run compare command I get next trace right after the banner

```
Traceback (most recent call last):
  File "/usr/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "<path-to-repo>/dotdrop/dotdrop/dotdrop.py", line 716, in <module>
    if main():
  File "<path-to-repo>/dotdrop/dotdrop/dotdrop.py", line 677, in main
    ret = cmd_compare(o, tmp)
  File "<path-to-repo>/dotdrop/dotdrop/dotdrop.py", line 252, in cmd_compare
    ret, insttmp = inst.install_to_temp(t, tmp, src, dotfile.dst)
  File "<path-to-repo>/dotdrop/dotdrop/installer.py", line 533, in install_to_temp
    ret, tmpdst = self._install_to_temp(templater, src, dst, tmpdir)
  File "<path-to-repo>/dotdrop/dotdrop/installer.py", line 513, in _install_to_temp
    return self.install(templater, src, tmpdst), tmpdst
  File "<path-to-repo>/dotdrop/dotdrop/installer.py", line 98, in install
    noempty=noempty, ignore=ignore)
  File "<path-to-repo>/dotdrop/dotdrop/installer.py", line 311, in _handle_file
    content = templater.generate(src)
  File "<path-to-repo>/dotdrop/dotdrop/templategen.py", line 75, in generate
    return self._handle_file(src)
  File "<path-to-repo>/dotdrop/dotdrop/templategen.py", line 132, in _handle_file
    return self._handle_text_file(src)
  File "<path-to-repo>/dotdrop/dotdrop/templategen.py", line 149, in _handle_text_file
    template = self.env.get_template(template_rel_path)
  File "<user-home>/.local/lib/python3.6/site-packages/jinja2/environment.py", line 830, in get_template
    return self._load_template(name, self.make_globals(globals))
  File "<user-home>/.local/lib/python3.6/site-packages/jinja2/environment.py", line 804, in _load_template
    template = self.loader.load(self, name, globals)
  File "<user-home>/.local/lib/python3.6/site-packages/jinja2/loaders.py", line 113, in load
    source, filename, uptodate = self.get_source(environment, name)
  File "<user-home>/.local/lib/python3.6/site-packages/jinja2/loaders.py", line 168, in get_source
    pieces = split_template_path(template)
  File "<user-home>/.local/lib/python3.6/site-packages/jinja2/loaders.py", line 31, in split_template_path
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: ../dotfiles-de/config/os_profile/Linux.zsh
```

According to this message there might be a problem in build relative path
`jinja2.exceptions.TemplateNotFound: ../dotfiles-de/config/os_profile/Linux.zsh` 
This step back `..` is unwanted.

**Steps to Reproduce**

1. Create two configs in the same folder with different dotpath also in the same folder
2. Import one into another
3. Run compare for profile from imported config 

**Expected behavior**

Should work with imported config files ) 

**Additional information**

main config file 
```yaml
config:
  backup: true
  banner: true
  create: true
  dotpath: dotfiles-common
  ignoreempty: false
  keepdot: false
  link_dotfile_default: nolink
  link_on_import: nolink
  longkey: false
  showdiff: false
  workdir: ~/.config/dotdrop
  import_configs: 
  - ./config-de.yaml
dotfiles:

profiles:
 
```
imported  config file 
```yaml
actions: 
  post:
    dconf-restore: dconf load / < /tmp/dconf-dump.ini
config:
  backup: true
  banner: true
  create: true
  dotpath: dotfiles-de
  ignoreempty: false
  keepdot: false
  link_dotfile_default: nolink
  link_on_import: nolink
  longkey: false
  showdiff: false
  workdir: ~/.config/dotdrop
dotfiles:
# <files>
profiles:
# <profiles> 
```

Thanks for a great dotfiles manager!

**Comment by deadc0de6** [comment]
Yep that's a bug, thanks for reporting it.
I'm investigating and will keep you updated. It's due to the way jinja2 is loading template files and the fact you have two different *dotpath* in your configs.

**Comment by deadc0de6** [comment]
It should be fixed in the [templatenotfound branch](https://github.com/deadc0de6/dotdrop/tree/templatenotfound), can you give a try before I merge it into master? Thanks!

**Comment by katoquro** [comment]
Thank you for fast replay! 

I still have the issue but with shorter trace ) 

And I want to say that may `Linux.zsh` isn't a template but I use templates in other files

```
Traceback (most recent call last):
  File "/usr/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "<path-to-repo>/dotdrop/dotdrop/dotdrop.py", line 722, in <module>
    if main():
  File "<path-to-repo>/dotdrop/dotdrop/dotdrop.py", line 683, in main
    ret = cmd_compare(o, tmp)
  File "<path-to-repo>/dotdrop/dotdrop/dotdrop.py", line 258, in cmd_compare
    ret, insttmp = inst.install_to_temp(t, tmp, src, dotfile.dst)
  File "<path-to-repo>/dotdrop/dotdrop/installer.py", line 533, in install_to_temp
    ret, tmpdst = self._install_to_temp(templater, src, dst, tmpdir)
  File "<path-to-repo>/dotdrop/dotdrop/installer.py", line 513, in _install_to_temp
    return self.install(templater, src, tmpdst), tmpdst
  File "<path-to-repo>/dotdrop/dotdrop/installer.py", line 98, in install
    noempty=noempty, ignore=ignore)
  File "<path-to-repo>/dotdrop/dotdrop/installer.py", line 311, in _handle_file
    content = templater.generate(src)
  File "<path-to-repo>/dotdrop/dotdrop/templategen.py", line 78, in generate
    return self._handle_file(src)
  File "<path-to-repo>/dotdrop/dotdrop/templategen.py", line 135, in _handle_file
    return self._handle_text_file(src)
  File "<path-to-repo>/dotdrop/dotdrop/templategen.py", line 161, in _handle_text_file
    template = self.env.get_template(template_rel_path)
  File "<home-dir>/.local/lib/python3.6/site-packages/jinja2/environment.py", line 830, in get_template
    return self._load_template(name, self.make_globals(globals))
  File "<home-dir>/.local/lib/python3.6/site-packages/jinja2/environment.py", line 804, in _load_template
    template = self.loader.load(self, name, globals)
  File "<home-dir>/.local/lib/python3.6/site-packages/jinja2/loaders.py", line 408, in load
    raise TemplateNotFound(name)
jinja2.exceptions.TemplateNotFound: ../dotfiles-de/config/os_profile/Linux.zsh

```

p.s.  
I had a version where `DOTDROP_AUTOUPDATE` feature was absent at ./dotdrop.sh so it always updates my git submodule ))) should I periodically copy the newest ./dotdrop.sh from submodule or this problem is already solved?

**Comment by katoquro** [comment]
I've tried to update deps `pip3 install --user -r dotdrop/requirements.txt` 

It just changed trace a bit

```
Traceback (most recent call last):
  File "/usr/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "<path-to-repo>/dotdrop/dotdrop/dotdrop.py", line 722, in <module>
    if main():
  File "<path-to-repo>/dotdrop/dotdrop/dotdrop.py", line 683, in main
    ret = cmd_compare(o, tmp)
  File "<path-to-repo>/dotdrop/dotdrop/dotdrop.py", line 258, in cmd_compare
    ret, insttmp = inst.install_to_temp(t, tmp, src, dotfile.dst)
  File "<path-to-repo>/dotdrop/dotdrop/installer.py", line 533, in install_to_temp
    ret, tmpdst = self._install_to_temp(templater, src, dst, tmpdir)
  File "<path-to-repo>/dotdrop/dotdrop/installer.py", line 513, in _install_to_temp
    return self.install(templater, src, tmpdst), tmpdst
  File "<path-to-repo>/dotdrop/dotdrop/installer.py", line 98, in install
    noempty=noempty, ignore=ignore)
  File "<path-to-repo>/dotdrop/dotdrop/installer.py", line 311, in _handle_file
    content = templater.generate(src)
  File "<path-to-repo>/dotdrop/dotdrop/templategen.py", line 78, in generate
    return self._handle_file(src)
  File "<path-to-repo>/dotdrop/dotdrop/templategen.py", line 135, in _handle_file
    return self._handle_text_file(src)
  File "<path-to-repo>/dotdrop/dotdrop/templategen.py", line 161, in _handle_text_file
    template = self.env.get_template(template_rel_path)
  File "<home-dir>/.local/lib/python3.6/site-packages/jinja2/environment.py", line 883, in get_template
    return self._load_template(name, self.make_globals(globals))
  File "<home-dir>/.local/lib/python3.6/site-packages/jinja2/environment.py", line 857, in _load_template
    template = self.loader.load(self, name, globals)
  File "<home-dir>/.local/lib/python3.6/site-packages/jinja2/loaders.py", line 429, in load
    raise TemplateNotFound(name)
jinja2.exceptions.TemplateNotFound: ../dotfiles-de/config/os_profile/Linux.zsh
```

**Comment by deadc0de6** [comment]
The fix isn't available in master or in pypi yet. You don't have to modify your dotfiles repository or your dotdrop submodule to test it, you could simply clone dotdrop's branch containing the fix somewhere else and make it point to your existing main config file. 

For example:
```bash
$ cd /tmp
$ git clone -b templatenotfound https://github.com/deadc0de6/dotdrop.git
$ cd dotdrop
$ ./dotdrop.sh compare -c <path-to-your-main-config.yaml>
```

So either my fix didn't work or you weren't actually running the version with the fix. Can you try the above and let me know if that produces the same issues?

**Comment by deadc0de6** [comment]
Regarding your question on auto-updating dotdrop, it's up to you how you want to update it but I would recommend to use the auto-update feature through the `dotdrop.sh` file so that you don't have to worry about doing any changes when dotdrop gets updated (especially since you use it as a submodule anyway). 

Just make sure there are not too many changes in the `dotdrop.sh` you use in comparison with the one present in master. If you have any doubts, feel free to post here and I'll to help you.

**Comment by katoquro** [comment]
About check: I pretty sure than tested your branch because lines numbers in a trace are related to the patch. 
With your example result is the same (including line numbers)

**Comment by deadc0de6** [comment]
Sorry, my bad you're right it wasn't completely fixed. Actually the issue came from the fact the main config file's dotpath didn't exist on the filesystem. It is now fixed!

Regarding updates, `dotdrop.sh` doesn't get updated automatically, you have to manually update it or copy the most recent version (it rarely changes so getting the latest version is good).

**Comment by deadc0de6** [comment]
This was merged into master and will be part of next release. Thanks again for your help on this!

**Comment by katoquro** [comment]
You are right I did typo dotfile**s**-common 😅 sorry 
Now it works perfectly even with my mistake 

How about such piece of bash here? 
https://github.com/deadc0de6/dotdrop/blob/templatenotfound/dotdrop.sh#L29

```
  if [ -f "dotdrop.sh" ] && [ -f "dotdrop/dotdrop.sh" ] ; then
	  cp -f dotdrop/dotdrop.sh dotdrop.sh
  fi
```

**Comment by deadc0de6** [comment]
Well unless you have changed a lot in `dotdrop.sh`, I would simply  replace yours with the latest in master (https://raw.githubusercontent.com/deadc0de6/dotdrop/master/dotdrop.sh).

**Comment by deadc0de6** [comment]
But yeah your idea of regularly updating it is a good one. I didn't want to auto-update the script itself since I think many people are tweaking it to their own liking and auto-update would overwrite their changes.
