### ISSUE TITLE
[bug] 

### ISSUE THREAD

**Issue by 0kto** [deadc0de6/dotdrop#256]
Dotdrop version (and git commit if run from source): v1.1.0
Using dotdrop: installed from AUR

**Describe the bug**

Importing a new file into dotdrop removes the empty fields `src` and `dst` of any empty dotfiles in the configuration file, leading to an immediate error.

**Steps to Reproduce**

1. Create a dotfile with content '...'

```
config:
  backup: true
  banner: false
  create: true
  dotpath: dotfiles
  ignoreempty: false
  keepdot: false
  longkey: true
  showdiff: true
  workdir: ~/.config/dotdrop
  link_on_import: nolink
  minversion: 1.1.0
actions:
  always_action: 'date > ~/.dotdrop.log'
dotfiles:
  fake:
    src:
    dst:
    actions:
    - always_action
profiles:
  x230:
    dotfiles:
    - fake
```
`actions` and `dotfiles` copied from the [wiki](https://github.com/deadc0de6/dotdrop/wiki/usage-actions)

2. import new file using `dotdrop import <path-to-new-file>

3. The config file is fine (the new file is imported correctly), but the empty `src` and `dst` keywords for all fake dotfiles are deleted from it, resulting in a
```
KeyError: 'dst'
```

**Expected behavior**

Parsing of the config file should not remove the empty `src` and `dst` keywords.

**Additional information**

Dotdrop's execution with the debug logs (`--verbose`)
```bash
$ dotdrop -c text.yaml import .tmux.conf --verbose
[DEBUG][dotdrop.options.__init__] version: 1.1.0
[DEBUG][dotdrop.options.__init__] config file: text.yaml
[DEBUG][dotdrop.cfg_yaml._norm_path] normalizing path dotfiles
[DEBUG][dotdrop.cfg_yaml._norm_path] normalizing path dotfiles relative to config file directory
[DEBUG][dotdrop.cfg_yaml._norm_path] normalizing path ~/.config/dotdrop
[DEBUG][dotdrop.cfg_yaml._parse_main_yaml] settings: {'backup': True, 'banner': False, 'create': True, 'dotpath': '/home/keep/mjk/dotfiles', 'ignoreempty': False, 'keepdo
t': False, 'link_dotfile_default': 'nolink', 'link_on_import': 'nolink', 'longkey': True, 'showdiff': True, 'workdir': '/home/keep/mjk/.config/dotdrop', 'minversion': '1.
1.0', 'diff_command': 'diff -r -u {0} {1}', 'default_actions': [], 'import_actions': [], 'import_configs': [], 'import_variables': [], 'cmpignore': [], 'upignore': [], 'i
nstignore': [], 'func_file': [], 'filter_file': []}
[DEBUG][dotdrop.cfg_yaml._parse_main_yaml] dotfiles: {'fake': ordereddict([('src', None), ('dst', None), ('actions', ['always_action']), ('link', 'nolink'), ('ignoreempty
', False)])}
[DEBUG][dotdrop.cfg_yaml._parse_main_yaml] profiles: {'x230': ordereddict([('dotfiles', ['fake'])])}
[DEBUG][dotdrop.cfg_yaml._parse_main_yaml] actions: {'always_action': ('post', 'date > ~/.dotdrop.log')}
[DEBUG][dotdrop.cfg_yaml._parse_main_yaml] trans_r: {}
[DEBUG][dotdrop.cfg_yaml._parse_main_yaml] trans_w: {}
[DEBUG][dotdrop.cfg_yaml._parse_main_yaml] variables: {}
[DEBUG][dotdrop.cfg_yaml._parse_main_yaml] dynvariables: {}                                                                                                      [169/499]
[DEBUG][dotdrop.cfg_yaml.__init__] before normalization: ordereddict([('config', ordereddict([('backup', True), ('banner', False), ('create', True), ('dotpath', 'dotfiles
'), ('ignoreempty', False), ('keepdot', False), ('longkey', True), ('showdiff', True), ('workdir', '~/.config/dotdrop'), ('link_on_import', 'nolink'), ('minversion', '1.1
.0')])), ('actions', ordereddict([('always_action', 'date > ~/.dotdrop.log')])), ('dotfiles', ordereddict([('fake', ordereddict([('src', None), ('dst', None), ('actions',
 ['always_action'])]))])), ('profiles', ordereddict([('x230', ordereddict([('dotfiles', ['fake'])]))])), ('trans_read', {}), ('trans_write', {}), ('variables', {}), ('dyn
variables', {})])
[DEBUG][dotdrop.cfg_yaml._merge_variables] get local variables
[DEBUG][dotdrop.cfg_yaml._norm_path] normalizing path /home/keep/mjk/dotfiles
[DEBUG][dotdrop.cfg_yaml._norm_path] normalizing path /home/keep/mjk/text.yaml
[DEBUG][dotdrop.cfg_yaml._norm_path] normalizing path /home/keep/mjk/.config/dotdrop
[DEBUG][dotdrop.cfg_yaml._norm_path] normalizing path /home/keep/mjk/dotfiles
[DEBUG][dotdrop.cfg_yaml._norm_path] normalizing path /home/keep/mjk/text.yaml
[DEBUG][dotdrop.cfg_yaml._norm_path] normalizing path /home/keep/mjk/.config/dotdrop
[DEBUG][dotdrop.cfg_yaml._debug_vars] variables:
[DEBUG][dotdrop.cfg_yaml._debug_vars]   "profile": x230
[DEBUG][dotdrop.cfg_yaml._debug_vars]   "_dotdrop_dotpath": /home/keep/mjk/dotfiles
[DEBUG][dotdrop.cfg_yaml._debug_vars]   "_dotdrop_cfgpath": /home/keep/mjk/text.yaml
[DEBUG][dotdrop.cfg_yaml._debug_vars]   "_dotdrop_workdir": /home/keep/mjk/.config/dotdrop
[DEBUG][dotdrop.cfg_yaml._merge_variables] local variables resolved
[DEBUG][dotdrop.cfg_yaml._debug_vars] variables:
[DEBUG][dotdrop.cfg_yaml._debug_vars]   "profile": x230
[DEBUG][dotdrop.cfg_yaml._debug_vars]   "_dotdrop_dotpath": /home/keep/mjk/dotfiles
[DEBUG][dotdrop.cfg_yaml._debug_vars]   "_dotdrop_cfgpath": /home/keep/mjk/text.yaml
[DEBUG][dotdrop.cfg_yaml._debug_vars]   "_dotdrop_workdir": /home/keep/mjk/.config/dotdrop
[DEBUG][dotdrop.cfg_yaml._norm_path] normalizing path /home/keep/mjk/dotfiles
[DEBUG][dotdrop.cfg_yaml._norm_path] normalizing path /home/keep/mjk/text.yaml
[DEBUG][dotdrop.cfg_yaml._norm_path] normalizing path /home/keep/mjk/.config/dotdrop
[DEBUG][dotdrop.cfg_yaml._merge_variables] resolve all uses of variables in config
[DEBUG][dotdrop.cfg_yaml._debug_vars] variables:
[DEBUG][dotdrop.cfg_yaml._debug_vars]   "profile": x230
[DEBUG][dotdrop.cfg_yaml._debug_vars]   "_dotdrop_dotpath": /home/keep/mjk/dotfiles
[DEBUG][dotdrop.cfg_yaml._debug_vars]   "_dotdrop_cfgpath": /home/keep/mjk/text.yaml
[DEBUG][dotdrop.cfg_yaml._debug_vars]   "_dotdrop_workdir": /home/keep/mjk/.config/dotdrop
[DEBUG][dotdrop.cfg_yaml.__init__] after normalization: ordereddict([('config', ordereddict([('backup', True), ('banner', False), ('create', True), ('dotpath', 'dotfiles'
), ('ignoreempty', False), ('keepdot', False), ('longkey', True), ('showdiff', True), ('workdir', '~/.config/dotdrop'), ('link_on_import', 'nolink'), ('minversion', '1.1.
0')])), ('actions', ordereddict([('always_action', 'date > ~/.dotdrop.log')])), ('dotfiles', ordereddict([('fake', ordereddict([('src', None), ('dst', None), ('actions',
['always_action'])]))])), ('profiles', ordereddict([('x230', ordereddict([('dotfiles', ['fake'])]))])), ('trans_read', {}), ('trans_write', {}), ('variables', {}), ('dynv
ariables', {})])
[DEBUG][dotdrop.cfg_aggregator._load] settings: <dotdrop.settings.Settings object at 0x7f2ae1417b80>
[DEBUG][dotdrop.cfg_aggregator._load] dotfiles: [dotfile(key:"fake", src:"", dst:"", link:"nolink")]
[DEBUG][dotdrop.cfg_aggregator._load] profiles: [profile(key:"x230")]
[DEBUG][dotdrop.cfg_aggregator._load] actions: [action(always_action: "date > ~/.dotdrop.log" (post))]
[DEBUG][dotdrop.cfg_aggregator._load] trans_r: []
[DEBUG][dotdrop.cfg_aggregator._load] trans_w: []
[DEBUG][dotdrop.cfg_aggregator._load] variables: {'profile': 'x230', '_dotdrop_dotpath': '/home/keep/mjk/dotfiles', '_dotdrop_cfgpath': '/home/keep/mjk/text.yaml[125/499]
rop_workdir': '/home/keep/mjk/.config/dotdrop'}
[DEBUG][dotdrop.cfg_aggregator._patch_keys_to_objs] patching dotfiles ...
[DEBUG][dotdrop.cfg_aggregator._patch_keys_to_objs] patching key:"x230".dotfiles with [dotfile(key:"fake", src:"", dst:"", link:"nolink")]
[DEBUG][dotdrop.cfg_aggregator._patch_keys_to_objs] patching actions ...
[DEBUG][dotdrop.cfg_aggregator._patch_keys_to_objs] patching key:"fake", src:"", dst:"", link:"nolink".actions with [action(always_action: "date > ~/.dotdrop.log" (post))
]
[DEBUG][dotdrop.cfg_aggregator._patch_keys_to_objs] patching actions ...
[DEBUG][dotdrop.cfg_aggregator._patch_keys_to_objs] patching default_actions ...
[DEBUG][dotdrop.cfg_aggregator._load] default actions: []
[DEBUG][dotdrop.cfg_aggregator._patch_keys_to_objs] patching trans_r ...
[DEBUG][dotdrop.cfg_aggregator._patch_keys_to_objs] patching trans_w ...
[DEBUG][dotdrop.options._read_config] new setting: backup=True
[DEBUG][dotdrop.options._read_config] new setting: banner=False
[DEBUG][dotdrop.options._read_config] new setting: create=True
[DEBUG][dotdrop.options._read_config] new setting: dotpath=/home/keep/mjk/dotfiles
[DEBUG][dotdrop.options._read_config] new setting: ignoreempty=False
[DEBUG][dotdrop.options._read_config] new setting: keepdot=False
[DEBUG][dotdrop.options._read_config] new setting: link_dotfile_default=nolink
[DEBUG][dotdrop.options._read_config] new setting: link_on_import=nolink
[DEBUG][dotdrop.options._read_config] new setting: longkey=True
[DEBUG][dotdrop.options._read_config] new setting: showdiff=True
[DEBUG][dotdrop.options._read_config] new setting: workdir=/home/keep/mjk/.config/dotdrop
[DEBUG][dotdrop.options._read_config] new setting: minversion=1.1.0
[DEBUG][dotdrop.options._read_config] new setting: diff_command=diff -r -u {0} {1}
[DEBUG][dotdrop.options._read_config] new setting: default_actions=[]
[DEBUG][dotdrop.options._read_config] new setting: import_actions=[]
[DEBUG][dotdrop.options._read_config] new setting: import_configs=[]
[DEBUG][dotdrop.options._read_config] new setting: import_variables=[]
[DEBUG][dotdrop.options._read_config] new setting: cmpignore=[]
[DEBUG][dotdrop.options._read_config] new setting: upignore=[]
[DEBUG][dotdrop.options._read_config] new setting: instignore=[]
[DEBUG][dotdrop.options._read_config] new setting: func_file=[]
[DEBUG][dotdrop.options._read_config] new setting: filter_file=[]
[DEBUG][dotdrop.options._debug_attr] CLI options:
[DEBUG][dotdrop.options._debug_attr] - args: {'--as': None,
 '--cfg': 'text.yaml',
 '--dry': False,
 '--file': [],
 '--force': False,
 '--force-actions': False,
 '--grepable': False,
 '--help': False,
 '--ignore': ['*.dotdropbak', '*.dotdropbak'],
 '--key': False,                                                                                                                                                  [81/499]
 '--link': None,
 '--no-banner': False,
 '--nodiff': False,
 '--profile': 'x230',
 '--show-patch': False,
 '--showdiff': False,
 '--temp': False,
 '--template': False,
 '--verbose': True,
 '--version': False,
 '<key>': [],
 '<path>': ['.tmux.conf'],
 'compare': False,
 'detail': False,
 'files': False,
 'import': True,
 'install': False,
 'profiles': False,
 'remove': False,
 'update': False}
[DEBUG][dotdrop.options._debug_attr] - backup: True
[DEBUG][dotdrop.options._debug_attr] - banner: False
[DEBUG][dotdrop.options._debug_attr] - cmd_compare: False
[DEBUG][dotdrop.options._debug_attr] - cmd_detail: False
[DEBUG][dotdrop.options._debug_attr] - cmd_files: False
[DEBUG][dotdrop.options._debug_attr] - cmd_import: True
[DEBUG][dotdrop.options._debug_attr] - cmd_install: False
[DEBUG][dotdrop.options._debug_attr] - cmd_profiles: False
[DEBUG][dotdrop.options._debug_attr] - cmd_remove: False
[DEBUG][dotdrop.options._debug_attr] - cmd_update: False
[DEBUG][dotdrop.options._debug_attr] - cmpignore: []
[DEBUG][dotdrop.options._debug_attr] - compare_focus: []
[DEBUG][dotdrop.options._debug_attr] - compare_ignore: ['*.dotdropbak']
[DEBUG][dotdrop.options._debug_attr] - conf: <dotdrop.cfg_aggregator.CfgAggregator object at 0x7f2ae17c79a0>
[DEBUG][dotdrop.options._debug_attr] - confpath: text.yaml
[DEBUG][dotdrop.options._debug_attr] - create: True
[DEBUG][dotdrop.options._debug_attr] - debug: True
[DEBUG][dotdrop.options._debug_attr] - default_actions: []
[DEBUG][dotdrop.options._debug_attr] - detail_keys: []
[DEBUG][dotdrop.options._debug_attr] - diff_command: diff -r -u {0} {1}
[DEBUG][dotdrop.options._debug_attr] - dotfiles: [dotfile(key:"fake", src:"", dst:"", link:"nolink")]
[DEBUG][dotdrop.options._debug_attr] - dotpath: /home/keep/mjk/dotfiles
[DEBUG][dotdrop.options._debug_attr] - dry: False
[DEBUG][dotdrop.options._debug_attr] - files_grepable: False                                                                                                      [37/499]
[DEBUG][dotdrop.options._debug_attr] - files_templateonly: False
[DEBUG][dotdrop.options._debug_attr] - filter_file: []
[DEBUG][dotdrop.options._debug_attr] - func_file: []
[DEBUG][dotdrop.options._debug_attr] - ignoreempty: False
[DEBUG][dotdrop.options._debug_attr] - import_actions: []
[DEBUG][dotdrop.options._debug_attr] - import_as: None
[DEBUG][dotdrop.options._debug_attr] - import_configs: []
[DEBUG][dotdrop.options._debug_attr] - import_link: nolink
[DEBUG][dotdrop.options._debug_attr] - import_path: ['.tmux.conf']
[DEBUG][dotdrop.options._debug_attr] - import_variables: []
[DEBUG][dotdrop.options._debug_attr] - install_backup_suffix: .dotdropbak
[DEBUG][dotdrop.options._debug_attr] - install_default_actions_post: []
[DEBUG][dotdrop.options._debug_attr] - install_default_actions_pre: []
[DEBUG][dotdrop.options._debug_attr] - install_diff: True
[DEBUG][dotdrop.options._debug_attr] - install_force_action: False
[DEBUG][dotdrop.options._debug_attr] - install_ignore: []
[DEBUG][dotdrop.options._debug_attr] - install_keys: []
[DEBUG][dotdrop.options._debug_attr] - install_showdiff: True
[DEBUG][dotdrop.options._debug_attr] - install_temporary: False
[DEBUG][dotdrop.options._debug_attr] - instignore: []
[DEBUG][dotdrop.options._debug_attr] - keepdot: False
[DEBUG][dotdrop.options._debug_attr] - link_dotfile_default: nolink
[DEBUG][dotdrop.options._debug_attr] - link_on_import: nolink
[DEBUG][dotdrop.options._debug_attr] - log: <dotdrop.logger.Logger object at 0x7f2ae17c7ee0>
[DEBUG][dotdrop.options._debug_attr] - longkey: True
[DEBUG][dotdrop.options._debug_attr] - minversion: 1.1.0
[DEBUG][dotdrop.options._debug_attr] - profile: x230
[DEBUG][dotdrop.options._debug_attr] - profiles: [profile(key:"x230")]
[DEBUG][dotdrop.options._debug_attr] - profiles_grepable: False
[DEBUG][dotdrop.options._debug_attr] - remove_iskey: False
[DEBUG][dotdrop.options._debug_attr] - remove_path: ['.tmux.conf']
[DEBUG][dotdrop.options._debug_attr] - safe: True
[DEBUG][dotdrop.options._debug_attr] - showdiff: True
[DEBUG][dotdrop.options._debug_attr] - update_ignore: ['*.dotdropbak']
[DEBUG][dotdrop.options._debug_attr] - update_iskey: False
[DEBUG][dotdrop.options._debug_attr] - update_path: ['.tmux.conf']
[DEBUG][dotdrop.options._debug_attr] - update_showpatch: False                                                                                                     [0/499]
[DEBUG][dotdrop.options._debug_attr] - upignore: []
[DEBUG][dotdrop.options._debug_attr] - variables: {'profile': 'x230', '_dotdrop_dotpath': '/home/keep/mjk/dotfiles', '_dotdrop_cfgpath': '/home/keep/mjk/text.yaml', '_dot
drop_workdir': '/home/keep/mjk/.config/dotdrop'}
[DEBUG][dotdrop.options._debug_attr] - workdir: /home/keep/mjk/.config/dotdrop
[DEBUG][dotdrop.dotdrop.main]


[DEBUG][dotdrop.dotdrop.main] running cmd: import
[DEBUG][dotdrop.dotdrop.cmd_importer] trying to import .tmux.conf
[DEBUG][dotdrop.dotdrop.cmd_importer] import dotfile: src:tmux.conf dst:/home/keep/mjk/.tmux.conf
[DEBUG][dotdrop.comparator.compare] comparing /home/keep/mjk/dotfiles/tmux.conf and /home/keep/mjk/.tmux.conf
[DEBUG][dotdrop.comparator.compare] ignore pattern(s): []
[DEBUG][dotdrop.comparator.compare] is file
[DEBUG][dotdrop.comparator._comp_file] compare file /home/keep/mjk/dotfiles/tmux.conf with /home/keep/mjk/.tmux.conf
[DEBUG][dotdrop.utils.run] exec: diff -r -u /home/keep/mjk/.tmux.conf /home/keep/mjk/dotfiles/tmux.conf
[DEBUG][dotdrop.dotdrop.cmd_importer] will overwrite: True
[DEBUG][dotdrop.utils.run] exec: mkdir -p /home/keep/mjk/dotfiles
[DEBUG][dotdrop.cfg_yaml._norm_path] normalizing path /home/keep/mjk/dotfiles/tmux.conf
[DEBUG][dotdrop.cfg_aggregator._create_new_dotfile] new dotfile key: f_tmux.conf
[DEBUG][dotdrop.cfg_yaml.add_dotfile] adding new dotfile: f_tmux.conf
[DEBUG][dotdrop.cfg_yaml.add_dotfile_to_profile] add "f_tmux.conf" to profile "x230"
[DEBUG][dotdrop.cfg_aggregator.new] new dotfile f_tmux.conf to profile x230
[DEBUG][dotdrop.cfg_yaml.save] saving to /home/keep/mjk/text.yaml
[DEBUG][dotdrop.cfg_aggregator.new] reloading config
Traceback (most recent call last):
  File "/usr/bin/dotdrop", line 33, in <module>
    sys.exit(load_entry_point('dotdrop==1.1.0', 'console_scripts', 'dotdrop')())
  File "/usr/lib/python3.8/site-packages/dotdrop/__init__.py", line 11, in main
    if dotdrop.dotdrop.main():
  File "/usr/lib/python3.8/site-packages/dotdrop/dotdrop.py", line 700, in main
    ret = cmd_importer(o)
  File "/usr/lib/python3.8/site-packages/dotdrop/dotdrop.py", line 435, in cmd_importer
    retconf = o.conf.new(src, dst, linktype)
  File "/usr/lib/python3.8/site-packages/dotdrop/cfg_aggregator.py", line 186, in new
    self._load()
  File "/usr/lib/python3.8/site-packages/dotdrop/cfg_aggregator.py", line 47, in _load
    self.cfgyaml = CfgYaml(self.path,
  File "/usr/lib/python3.8/site-packages/dotdrop/cfg_yaml.py", line 129, in __init__
    self._resolve_dotfile_paths()
  File "/usr/lib/python3.8/site-packages/dotdrop/cfg_yaml.py", line 242, in _resolve_dotfile_paths
    dst = dotfile[self.key_dotfile_dst]
  File "/usr/lib/python3.8/site-packages/ruamel/yaml/comments.py", line 753, in __getitem__
    return ordereddict.__getitem__(self, key)
KeyError: 'dst'
```

**Comment by deadc0de6** [comment]
Thanks for reporting this! It is indeed a bug, I'll work on it.

**Comment by deadc0de6** [comment]
I have fixed the bug in the [bug250 branch](https://github.com/deadc0de6/dotdrop/tree/bug250) directly since this is related to the refactoring of the lower level config (see [this issue for more info](https://github.com/deadc0de6/dotdrop/issues/250)). I plan on merging this over the week-end and will release a new version at the same time.

If you need it right now, you can always use dotdrop from source and switch to the above branch. I'll make it fast I promise!

**Comment by 0kto** [comment]
It is easy enough to work around (just add the two keys to the config file), so don't worry about it being high priority!
Thanks a lot for the fast fix!

**Comment by deadc0de6** [comment]
The fix has been merged into master and is available in the git version. You can use that version with the [dotdrop-git](https://aur.archlinux.org/packages/dotdrop-git/) aur package.

I'll release a new version as soon as I have migrated the doc to readthedocs.

**Comment by gusbemacbe** [comment]
@deadc0de6 

I am still having this problem. I updated with AUR of both `dotdrop` and `dotdrop-git`, but the same problem insists.

**Comment by deadc0de6** [comment]
Yeah that was a different bug :-s. 

It should now be fixed in the master branch (using [dotdrop-git](https://aur.archlinux.org/packages/dotdrop-git/) from aur would work).

**Comment by gusbemacbe** [comment]
@deadc0de6 

It worked now. Thank you!
