### ISSUE TITLE
Symlinked dotfiles with templating are directly linked

### ISSUE THREAD

**Issue by fennerm** [deadc0de6/dotdrop#56]
The README states that symlinked dotfiles with templating are first installed into ~/.config/dotdrop and then linked from there. Instead dotdrop seems to just link the files directly without templating. Looking through the source code, it seems like some steps are definitely missing (e.g workdir is never used as far as I can tell).

**Comment by fennerm** [comment]
Oh it looks like you're in the middle of implementing this, nvm

**Comment by deadc0de6** [comment]
@fennerm yes I was implementing that however I'm surprised you got a non-working version in the master branch. Maybe some race conditions when pulling. Anyway, it should work now, let me know if you find any issue.

**Comment by fennerm** [comment]
This still isn't working correctly for me. Just pulled the latest version and dotfiles with env variables are being directly linked.

**Comment by deadc0de6** [comment]
Ok, can you provide me with more info as I am unable to reproduce your issue. Below is a small test I've done that is successfully linking a dotfile using env variables.

```bash
# dotdrop version
$ ./dotdrop.sh --version          
0.20.1

# the test dotfile with env variable
$ cat dotfiles/test-file 
test
{{@@ env['MY_VAR'] @@}}

# relevant part of the config file
$ cat config.yaml
...
dotfiles:
  f_test-file:
    dst: ~/.test-file
    src: test-file
    link: true
...

# installation of the dotfile
$ MY_VAR=env-test ./dotdrop.sh install
	-> copied "~/dotfiles/dotfiles/test-file" to "~/.config/dotdrop/.test-file"
	-> linked "~/.test-file" to "~/.config/dotdrop/.test-file"

1 dotfile(s) installed.

# dotfile is a link
$ ls -l .test-file    
.test-file -> /home/user/.config/dotdrop/.test-file

# and variable are substituted
$ cat ~/.test-file           
test
env-test
```

Can you reproduce the above behavior?
Could you provide me with more info on your setup (dotdrop version, OS, dotdrop config file, example of dotfile being installed, result situation, logs, debug logs if possible, etc)?

**Comment by deadc0de6** [comment]
Maybe the reason your file is linked directly is that it is not interpreted as a template. Are you sure to use the correct template directives (see the [doc on templating](https://github.com/deadc0de6/dotdrop#templating))?

For example for a env variable it would be `{{@@ env['MY_VAR'] @@}}`

**Comment by fennerm** [comment]
Nope turns out that my dotdrop installation had just become out of sync somehow. Maybe because I didn't run ./dotdrop/bootstrap.sh after my last update? My bad, thank you for helping out anyway.
